"""Low-risk OpenTelemetry attribute names used by the runtime."""

RUNTIME_VERSION = "agent.runtime.version"
RUN_ID = "agent.run.id"
THREAD_ID = "agent.thread.id"
REQUEST_ID = "agent.request.id"
AGENT_ID = "agent.id"
AGENT_VERSION = "agent.version"
AGENT_FRAMEWORK = "agent.framework"
MESSAGE_COUNT = "agent.message.count"
TOOL_NAME = "agent.tool.name"
HOOK_PHASE = "agent.hook.phase"
GUARDRAIL_NAME = "agent.guardrail.name"
FEEDBACK_ID = "agent.feedback.id"
FEEDBACK_TYPE = "agent.feedback.type"
